### ISSUE TITLE
Cannot connect to Hive database with Zookpeer Discovery enabled

### ISSUE THREAD

**Issue by pranaysahith** [timveil/hive-jdbc-uber-jar#15]
Hi,

I am trying to connect to Hive from dbeaver using library - 

> https://github.com/timveil/hive-jdbc-uber-jar/releases/download/v1.9-2.6.5/hive-jdbc-uber-2.6.5.0-292.jar

The database has zookeeper discovery enabled.
But the connection fails with below error:

> org.apache.hive.jdbc.ZooKeeperHiveClientException: Unable to read HiveServer2 configs from ZooKeeper
  Unable to read HiveServer2 configs from ZooKeeper
  Unable to read HiveServer2 configs from ZooKeeper
    A HostProvider may not be empty!

The hostname looks like this -

> zookeeperhost1:2181,zookeeperhost12:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2

I am able to connect to the same host using beeline.
Can you please let me know if I am missing something?
Thanks!

**Comment by shursulei** [comment]
> Hi,
> 
> I am trying to connect to Hive from dbeaver using library -
> 
> > https://github.com/timveil/hive-jdbc-uber-jar/releases/download/v1.9-2.6.5/hive-jdbc-uber-2.6.5.0-292.jar
> 
> The database has zookeeper discovery enabled.
> But the connection fails with below error:
> 
> > org.apache.hive.jdbc.ZooKeeperHiveClientException: Unable to read HiveServer2 configs from ZooKeeper
> > Unable to read HiveServer2 configs from ZooKeeper
> > Unable to read HiveServer2 configs from ZooKeeper
> > A HostProvider may not be empty!
> 
> The hostname looks like this -
> 
> > zookeeperhost1:2181,zookeeperhost12:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2
> 
> I am able to connect to the same host using beeline.
> Can you please let me know if I am missing something?
> Thanks!

Hi,I have this questions.How you solve this promble.Thanks !!

**Comment by pranaysahith** [comment]
While connecting use a hostname like :
**clustername**.azurehdinsight.net:443/default;ssl=true?hive.server2.transport.mode=http;hive.server2.thrift.http.path=/hive2

Leave database name **blank**
Set port number to **10000**
username should be in **username@domainname** format.
It should work
