### ISSUE TITLE
Connect to Secure Hive

### ISSUE THREAD

**Issue by andrzej-jedrzejewski** [timveil/hive-jdbc-uber-jar#4]
How can I connect with HiVe that is secured with Kerberos and SASL?
For beeline I use following string connection:
beeline -u "jdbc:hive2://ServerName:10000/default;principal=hive/ServerName@REALM;saslQop=auth-conf" 

Thanks,
Andrzej

**Comment by timveil** [comment]
i've just updated the project and jar to support kerberized clusters.  I haven't tested specifically with the SASL configuration you mentioned but prior to this change kerberos would not have worked at all.  Please have a look at release v1.3-2.5.3 and the updated documentation.  Let me know how it looks.

Tim
