### ISSUE TITLE
HIve Uber JDBC Jar Work with Hive LLAP

### ISSUE THREAD

**Issue by Rishabh-Miglani** [timveil/hive-jdbc-uber-jar#7]
Hey , 

Wanted to check with you , for the compatibility of creating this process for hive LLAP . Does the Jar produced here work with Hive LLAP as well ???

**Comment by timveil** [comment]
short answer is yes, you should be able to use the driver produced here to connect to a HS2 instance running LLAP (hive 2.x).  that is my setup at home during testing.
