### ISSUE TITLE
log4j included?

### ISSUE THREAD

**Issue by ebuildy** [timveil/hive-jdbc-uber-jar#8]
Trying to use this jar with Apache Zeppelin, I got the error:

``java.lang.IllegalStateException: Detected both log4j-over-slf4j.jar AND slf4j-log4j12.jar on the class path, preempting StackOverflowError.`` 

Is log4j included in your uber jar?

**Comment by timveil** [comment]
it is.  i had it in there to ensure consistent logging, especially in tools like dbvisualizer.  reality is that it could/should probably be removed and rely on the consumer to provide an actual SLF4J implementation.

**Comment by timveil** [comment]
i've released a new version which removes log4j
