### ISSUE TITLE
SLF4J dependency in DbVisualizer

### ISSUE THREAD

**Issue by kirmandi** [timveil/hive-jdbc-uber-jar#9]
trying to update hive-jdbc-uber-jar in DbVisualizer 10 throws following exception on connection:
> An error occurred while establishing the connection:
> 
> Details:
>    Type: java.lang.reflect.UndeclaredThrowableException
> 
> Stack Trace:
> java.lang.IllegalStateException: org.slf4j.LoggerFactory in failed state. Original exception was thrown EARLIER. See also http://www.slf4j.org/codes.html#unsuccessfulInit
>    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:422)
>    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
>    at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
>    at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:290)
>    at org.apache.hive.jdbc.HiveConnection.<clinit>(HiveConnection.java:111)
> [wrapped] java.lang.ExceptionInInitializerError
>    at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>    at java.lang.reflect.Method.invoke(Unknown Source)
>    at com.onseven.dbvis.g.B.D.ā(Z:1548)
>    at com.onseven.dbvis.g.B.F$A.call(Z:1369)
> [wrapped] java.lang.Exception: java.lang.ExceptionInInitializerError
>    at com.onseven.dbvis.g.B.F$A.call(Z:2374)
>    at java.util.concurrent.FutureTask.run(Unknown Source)
> [wrapped] java.lang.reflect.UndeclaredThrowableException
>    at com.sun.proxy.$Proxy0.connect(Unknown Source)
>    at com.onseven.dbvis.db.I.H.Ŋ(Z:2070)
>    at com.onseven.dbvis.db.I.H.Ĵ(Z:1692)
>    at com.onseven.dbvis.db.I.K.Ĵ(Z:3063)
>    at com.onseven.dbvis.db.I.D.ĥ(Z:1756)
>    at com.onseven.dbvis.K.C.W.ğ(Z:503)
>    at com.onseven.dbvis.K.C.J.Ă(Z:1374)
>    at com.onseven.dbvis.K.C.J.doInBackground(Z:1521)
>    at javax.swing.SwingWorker$1.call(Unknown Source)
>    at java.util.concurrent.FutureTask.run(Unknown Source)
>    at javax.swing.SwingWorker.run(Unknown Source)
>    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>    at java.lang.Thread.run(Unknown Source)

used version: hive-jdbc-uber-2.6.2.0-205.jar
using the earlier version hive-jdbc-uber-2.6.1.0-129.jar works just fine

**Comment by timveil** [comment]
thanks for reporting the issue.  let me investigate.

**Comment by timveil** [comment]
should be resolved now.  please download the latest release and retest
